server:
  port: 8000

spring:
  output.ansi.enabled: NEVER
  application:
    name: poc-spring-boot
  jackson:
    serialization-inclusion: NON_EMPTY
    serialization:
      write-dates-as-timestamps: false
    property-naming-strategy: SNAKE_CASE
